### PR TITLE
Piano Keyboard, TV Show Basics

### PR DESCRIPTION
**Pull request by Cadecicc**
I made it so that you can play the piano using the keyboard (currently capped at 4 notes at once, can make more audio sources as needed). Known bug: still don’t know how to smoothly quit out of it and get player movement working after.

Also, made a new test scene for the TV show! Works really nicely and you can preview it in the TestTVShow scene!

### CODE REVIEW

**Review by amandafleischer — COMMENTED** [review]
Love the idea of the TV show, it is going to look really cool! Even just the basic animations so far look good. Also, love the use of the keyboard for the piano! Much easier than clicking the keys with the mouse.
I see in InputManager.cs the created methods to enable and disable player movement upon starting the piano, and exiting the area. I know we were talking about it earlier not working properly, but is this still being worked out or just not working for me?

**Comment by Cadecicc** [comment]
> Love the idea of the TV show, it is going to look really cool! Even just the basic animations so far look good. Also, love the use of the keyboard for the piano! Much easier than clicking the keys with the mouse.
> I see in InputManager.cs the created methods to enable and disable player movement upon starting the piano, and exiting the area. I know we were talking about it earlier not working properly, but is this still being worked out or just not working for me?

The known bug I have is that you can’t exit when you enter it. The input actions still aren’t enabling properly so I still have to figure that out

**Review by amandafleischer — APPROVED** [review]

**Comment by amandafleischer** [comment]
> > Love the idea of the TV show, it is going to look really cool! Even just the basic animations so far look good. Also, love the use of the keyboard for the piano! Much easier than clicking the keys with the mouse.
> > I see in InputManager.cs the created methods to enable and disable player movement upon starting the piano, and exiting the area. I know we were talking about it earlier not working properly, but is this still being worked out or just not working for me?
> 
> The known bug I have is that you can’t exit when you enter it. The input actions still aren’t enabling properly so I still have to figure that out

Got it, sounds good!

**Review by JaredIsrael — APPROVED** [review]
LGTM!

**Pull request merged**
